# Generated by Django 4.1.3 on 2022-11-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AP_Dispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ap_nombre', models.CharField(help_text='Ingrese el Nombre', max_length=100)),
                ('ap_marca', models.CharField(help_text='Ingrese la Marca', max_length=100)),
                ('ap_precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('ap_descripcion', models.CharField(help_text='Ingrese una Descripcion', max_length=100)),
            ],
            options={
                'verbose_name': 'ap_dispositivo',
                'verbose_name_plural': 'ap_dispositivos',
            },
        ),
    ]
